# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-15 22:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_auto_20181015_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maker', to='first_app.User'),
        ),
    ]
