# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-16 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_auto_20181016_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='creator',
            new_name='user_id',
        ),
    ]
