# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-16 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_auto_20181016_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='user_id',
            new_name='creator',
        ),
    ]
