# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-17 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0015_auto_20181016_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='first_app.User'),
            preserve_default=False,
        ),
    ]
